"""Add terms_accepted and age_confirmed fields to users

Revision ID: 4212d91048b1
Revises: d36655a3e802
Create Date: 2025-11-12 14:15:21.416568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4212d91048b1'
down_revision: Union[str, None] = 'd36655a3e802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('terms_accepted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('age_confirmed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age_confirmed')
    op.drop_column('users', 'terms_accepted')
    # ### end Alembic commands ###
