"""Add medication and tracking tables

Revision ID: 5419e5404759
Revises: 4212d91048b1
Create Date: 2025-11-19 10:53:30.887770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5419e5404759'
down_revision: Union[str, None] = '4212d91048b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_medications_id'), 'user_medications', ['id'], unique=False)
    op.create_index(op.f('ix_user_medications_user_id'), 'user_medications', ['user_id'], unique=False)
    op.create_table('user_tracking_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_code', sa.String(), nullable=False),
    sa.Column('topic_label', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_code', name='uq_user_topic')
    )
    op.create_index(op.f('ix_user_tracking_topics_id'), 'user_tracking_topics', ['id'], unique=False)
    op.create_index(op.f('ix_user_tracking_topics_user_id'), 'user_tracking_topics', ['user_id'], unique=False)
    op.add_column('user_reminders', sa.Column('medication_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_reminders_medication_id'), 'user_reminders', ['medication_id'], unique=False)
    op.create_foreign_key(None, 'user_reminders', 'user_medications', ['medication_id'], ['id'])
    op.add_column('user_settings', sa.Column('takes_medication', sa.Boolean(), nullable=True))
    op.add_column('user_settings', sa.Column('wants_medication_reminders', sa.Boolean(), nullable=True))
    op.add_column('user_settings', sa.Column('wants_additional_tracking', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'wants_additional_tracking')
    op.drop_column('user_settings', 'wants_medication_reminders')
    op.drop_column('user_settings', 'takes_medication')
    op.drop_constraint(None, 'user_reminders', type_='foreignkey')
    op.drop_index(op.f('ix_user_reminders_medication_id'), table_name='user_reminders')
    op.drop_column('user_reminders', 'medication_id')
    op.drop_index(op.f('ix_user_tracking_topics_user_id'), table_name='user_tracking_topics')
    op.drop_index(op.f('ix_user_tracking_topics_id'), table_name='user_tracking_topics')
    op.drop_table('user_tracking_topics')
    op.drop_index(op.f('ix_user_medications_user_id'), table_name='user_medications')
    op.drop_index(op.f('ix_user_medications_id'), table_name='user_medications')
    op.drop_table('user_medications')
    # ### end Alembic commands ###
