"""Add questionnaire support and user profile fields

Revision ID: d36655a3e802
Revises: 71aad13d45fc
Create Date: 2025-11-12 13:38:07.611997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36655a3e802'
down_revision: Union[str, None] = '71aad13d45fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_id', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'questionnaire_id', name='uq_user_questionnaire')
    )
    op.create_index(op.f('ix_questionnaire_completions_id'), 'questionnaire_completions', ['id'], unique=False)
    op.create_index(op.f('ix_questionnaire_completions_questionnaire_id'), 'questionnaire_completions', ['questionnaire_id'], unique=False)
    op.create_index(op.f('ix_questionnaire_completions_user_id'), 'questionnaire_completions', ['user_id'], unique=False)
    op.create_table('user_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('condition_code', sa.String(), nullable=False),
    sa.Column('condition_label', sa.String(), nullable=False),
    sa.Column('condition_system', sa.String(), nullable=True),
    sa.Column('diagnosed_by_physician', sa.Boolean(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('physician_frequency', sa.String(), nullable=True),
    sa.Column('diabetes_type', sa.String(), nullable=True),
    sa.Column('therapy_type', sa.String(), nullable=True),
    sa.Column('wants_glucose_reminders', sa.Boolean(), nullable=True),
    sa.Column('pain_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'condition_code', name='uq_user_condition')
    )
    op.create_index(op.f('ix_user_conditions_id'), 'user_conditions', ['id'], unique=False)
    op.create_index(op.f('ix_user_conditions_user_id'), 'user_conditions', ['user_id'], unique=False)
    op.create_table('user_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_reminders_id'), 'user_reminders', ['id'], unique=False)
    op.create_index(op.f('ix_user_reminders_user_id'), 'user_reminders', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_country', sa.String(), nullable=True),
    sa.Column('store_region', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('daily_routine', sa.String(), nullable=True),
    sa.Column('ethnicity', sa.String(), nullable=True),
    sa.Column('hispanic_latino', sa.String(), nullable=True),
    sa.Column('allow_medical_support', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('language_preference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_legacy_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_legacy_user')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'age')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_reminders_user_id'), table_name='user_reminders')
    op.drop_index(op.f('ix_user_reminders_id'), table_name='user_reminders')
    op.drop_table('user_reminders')
    op.drop_index(op.f('ix_user_conditions_user_id'), table_name='user_conditions')
    op.drop_index(op.f('ix_user_conditions_id'), table_name='user_conditions')
    op.drop_table('user_conditions')
    op.drop_index(op.f('ix_questionnaire_completions_user_id'), table_name='questionnaire_completions')
    op.drop_index(op.f('ix_questionnaire_completions_questionnaire_id'), table_name='questionnaire_completions')
    op.drop_index(op.f('ix_questionnaire_completions_id'), table_name='questionnaire_completions')
    op.drop_table('questionnaire_completions')
    # ### end Alembic commands ###
